system/payingGuest/payingGuest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.urls import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pg/', include('pg.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

system/payingGuest/pg/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.pg_list, name = 'pg_list'),

    path('create/', views.pg_create, name = 'pg_create'),

    path('<int:pg_id>/edit/', views.pg_edit, name = 'pg_edit'),

    path('<int:pg_id>/delete/', views.pg_delete, name = 'pg_delete'),

    path('complaint/', views.send_complaint, name='send_complaint'),

    path('success/', views.success_view, name='success_view'),

    path('register/', views.registration, name='registration'),
]

system/payingGuest/pg/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class pgRoom(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.TextField(max_length=500)
    photo = models.ImageField(upload_to="photos/", blank=True, null=True, default='default.jpg')
    room = models.TextField(max_length=50)
    price = models.IntegerField()
    food = models.TextField(max_length=50)
    complaint = models.TextField(max_length=5000)

    def __str__(self):
        return f'{self.user.username} - {self.location} - {self.room}'

class complaintForm(models.Model):
    email = models.CharField(max_length=500)
    complaint = models.TextField(max_length=5000)

    def __str__(self):
        return f'{self.email} - {self.complaint}'

system/payingGuest/pg/forms.py
from django import forms 
from .models import pgRoom, complaintForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class pgForm(forms.ModelForm):
    class Meta:
        model = pgRoom
        fields = ['user', 'location', 'photo', 'room', 'price', 'food']

class pgComplaint(forms.ModelForm):
    class Meta:
         model = complaintForm
         email = forms.EmailField(label="email")
         complaint = forms.CharField(widget=forms.Textarea, label="complaint")
         fields = ['email', 'complaint']

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

system/payingGuest/pg/views.py
from django.shortcuts import render, redirect
from .models import pgRoom, complaintForm
from .forms import pgForm, pgComplaint, UserRegistrationForm
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.http import HttpResponseForbidden

# Create your views here.

def index(request):
    return render(request, 'index.html')

def pg_list(request):
    PGs = pgRoom.objects.all().order_by('price')
    return render(request, 'pg_list.html', {'PGs': PGs})

@login_required
def pg_create(request):
    if pgRoom.objects.filter(user=request.user).exists():
        return render(request,'pg_list.html', {'already_created': True})

    if request.method == "POST":
        form = pgForm(request.POST, request.FILES)
        if form.is_valid():
            pg = form.save(commit=False)
            pg.user = request.user
            pg.save()
            return redirect('pg_list')
    else:
        form = pgForm()
    return render(request, 'pg_form.html', {'form': form})

@login_required
def pg_edit(request, pg_id):
    pg = get_object_or_404(pgRoom, pk=pg_id, user = request.user)
    if request.method == 'POST':
        form = pgForm(request.POST, request.FILES, instance = pg)
        if form.is_valid():
            pg = form.save(commit = False)
            pg.user = request.user
            pg.save()
            return redirect('pg_list')
    else:
        form = pgForm(instance = pg)
    return render(request, 'pg_form.html', {'form': form})

@login_required
def pg_delete(request, pg_id):
    pg = get_object_or_404(pgRoom, pk=pg_id, user = request.user)
    if request.method == 'POST':
        pg.delete()
        return redirect('pg_list')
    return render(request, 'pg_confirm_delete.html', {'pg': pg})

# Sending a complaint via Email
def send_complaint(request):
    if request.method == "POST":
        form = pgComplaint(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            complaint = form.cleaned_data['complaint']
            # Send the email
            send_mail(
                'Complaint from Paying Guest Management System',  # Subject
                complaint,                    # Message body
                settings.DEFAULT_FROM_EMAIL,  # From email
                [email],            # To email list
                fail_silently=False,
            )
            return redirect('success_view')  # Redirect to a success page or thank you message
    else:
        form = pgComplaint()

    return render(request, 'pg_complaint.html', {'form': form})

# views.py
def success_view(request):
    return render(request, 'success.html')

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            return redirect('pg_list')
    else:
        form = UserRegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

system/payingGuest/pg/templates/index.html
{% extends "base.html" %}

{% block title %}
Paying Guest
{% endblock %}

{% block content %}
<h1 class="text-center mt-4"> Welcome to the Paying Guest Management System! </h1>
{% endblock %}

































{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background-color: black;
            color: white
        }
    </style>
</head>
<body>
    Test template
</body>
</html> {% endcomment %}

system/payingGuest/pg/templates/pg_complaint.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title %}
Paying Guest Complaint
{% endblock %}

{% block content %}
<h1 class="text-center mt-4"> Welcome to the Paying Guest Management System! </h1>

<h1 class="text-center">Submit a Complaint</h1>
<form method="post" class="p-4 border rounded">
    {% csrf_token %}

    <div class="mb-3">
        <label for="id_email" class="form-label">Email</label>
        {{ form.email|add_class:"form-control" }}
    </div>

    <div class="mb-3">
        <label for="id_complaint" class="form-label">Complaint</label>
        {{ form.complaint|add_class:"form-control" }}
    </div>

    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary">Send Complaint</button>
    </div>
</form>






{% comment %} <h1>Submit a Complaint</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send Complaint</button>
</form> {% endcomment %}


{% endblock %}

system/payingGuest/pg/templates/pg_confirm_delete.html
{% extends "base.html" %}

{% block title %}
Paying Guest
{% endblock %}

{% block content %}

<h1 class="text-center mt-4"> Welcome to the Paying Guest Management System! </h1>

<h1 class="text-center mt-4">Are you sure you want to DELETE your Form?</h1>

<form method = "post" class = "text-center">
{% csrf_token %}
    <button class="btn btn-danger mx-2">Delete</button>
    <a href="{% url 'pg_list' %}" class="btn btn-success">Cancel</a>
</form>

{% endblock %}

system/payingGuest/pg/templates/pg_form.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title %}
Paying Guest
{% endblock %}

{% block content %}
<h1 class="text-center mt-4"> 
    Welcome to the Paying Guest Management System! 
</h1>

<h2 class='text-center mt-4'>
    {% if form.instance.pk %}
    Change details
    {% else %}
    Create a new User
    {% endif %}

    <form method="post" enctype="multipart/form-data" class="p-4 border rounded shadow-sm">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_user" class="form-label">User</label>
            {{ form.user|add_class:"form-select" }}
        </div>
        
        <div class="mb-3">
            <label for="id_location" class="form-label">Location</label>
            {{ form.location|add_class:"form-control" }}
        </div>
        
        <div class="mb-3">
            <label for="id_photo" class="form-label">Photo</label>
            {{ form.photo|add_class:"form-control" }}
        </div>
        
        <div class="mb-3">
            <label for="id_room" class="form-label">Room</label>
            {{ form.room|add_class:"form-control" }}
        </div>
        
        <div class="mb-3">
            <label for="id_price" class="form-label">Price</label>
            {{ form.price|add_class:"form-control" }}
        </div>
        
        <div class="mb-3">
            <label for="id_food" class="form-label">Food</label>
            {{ form.food|add_class:"form-control" }}
        </div>
        
        <button class="btn btn-warning w-100" type="submit">
            Confirm Details
        </button>
    </form>    

    <a href="{% url 'pg_list' %}"> Back to PG</a>
</h2>
{% endblock %}

system/payingGuest/pg/templates/pg_list.html
{% extends "base.html" %}

{% block title %}
Paying Guest
{% endblock %}

{% block content %}
<h1 class="text-center mt-4"> Welcome to the Paying Guest Management System! </h1>

{% if already_created %}
  <p>You have filled the form. Thank you!!</p>
{% else %}
  <a class="btn btn-primary mb-4" href="{% url 'pg_create' %}">
    Fill your Form
  </a>
{% endif %} 

<div class="container row gap-3">
    {% for PG in PGs %}
    <div class="card" style="width: 18rem;">
        <img src="{{PG.photo.url}}" class="card-img-top" alt="default.jpg">
        <div class="card-body">
          <h5 class="card-title">Name - {{PG.user}}</h5>
          <p class="card-text">Location - {{PG.location}}</p>
          <p class="card-text">Room type - {{PG.room}}</p>
          <p class="card-text">Price - {{PG.price}}</p>
          <p class="card-text">Food preference - {{PG.food}}</p>
          {% if PG.user == user %}
          <a href="{% url 'pg_edit' PG.id %}" class="btn btn-primary">Change details</a>
          <a href="{% url 'pg_delete' PG.id %}" class="btn btn-danger">Delete</a>
          {% endif %}
        </div>
      </div>
    {% endfor %}
</div>

<form method="post">
  {% csrf_token %}
  <a class="btn btn-primary mb-4 mt-4" href="{% url 'send_complaint' %}">
      Send Complaint
  </a> 
</form>

{% endblock %}

system/payingGuest/pg/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <h1>Thank you for your complaint. We will get back to you soon.</h1>
</body>
</html>

system/payingGuest/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>
        {% block title %}
        PG
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">PG Management System</a>
            <div class="display-flex justify-content-end align-items-center">
              <a href="{% url 'pg_list' %}" class="btn btn-primary mx-2">Home</a>
              {% if user.is_authenticated %}
              <form method="post" action="{% url 'logout' %}" class="d-inline-block">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Logout</button>
              </form>
              {% else %}
              <a href="{% url 'registration' %}" class="btn btn-danger mx-2">New User?</a>
              <a href="{% url 'login' %}" class="btn btn-success mx-2">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>